name: Docker tests
run-name: ${{ github.actor }} is running the test schedules.
on:
  push:
    branches:
      - main
  pull_request:
    

jobs:
  run-scripts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pgver: [14, 15, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout lolor
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up docker-compose
      uses: docker/setup-compose-action@v1

    - name: Build and run docker images
      continue-on-error: true
      run: |
        cd docker
        docker build --build-arg PGVER=${{ matrix.pgver }} -t lolor -f Dockerfile.el9 .
        docker build --build-arg PGVER=${{ matrix.pgver }} -t lolor-tester -f Dockerfile.tester .
        docker compose up -d
   
    - name: Wait for tests to complete
      continue-on-error: true
      run: |
        while [ "$(docker inspect -f '{{.State.Running}}' tester)" == "true" ]; do
          echo "Waiting for tests to complete..."
          sleep 1
        done
        docker logs n1
        docker logs n2
        docker logs n3
        grep -Eq "FAIL|ERROR" tests/out.txt && exit 1 || exit 0

    - name: Upload Log File as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: latest-log-${{ matrix.pgver }}
        path: tests/out.txt
